import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  atRuleDeclarationsThatNeverApply,
  describe,
  stylesheetOrder,
} from './cascade-check.mjs';

const failures = [];
const requiredFiles = [
  'public/robots.txt',
  'public/manifest.json',
  'public/favicon.svg',
  'public/og-image.png',
  'public/llms.txt',
];
for (const file of requiredFiles) {
  if (!existsSync(file)) failures.push(`Missing required file: ${file}`);
}

const index = readFileSync('index.html', 'utf8');
for (const token of ['<title>', 'name="description"', 'rel="canonical"', 'application/ld+json']) {
  if (!index.includes(token)) failures.push(`Missing metadata: ${token}`);
}
if (index.includes('analytics.giveabit.io/script.js')) failures.push('Analytics must be runtime-gated, not hard-coded in index.html');

// ── The machine-readable surface ──────────────────────────────────────────────
// Structured data is the one part of the site nothing renders, so nothing notices when it
// breaks: a malformed block is dropped by every consumer in silence, and a `Person` whose
// email is an address nobody reads is still valid JSON. Both are checked here.
const ldBlocks = [...index.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)].map(
  (match) => match[1],
);
if (!ldBlocks.length) failures.push('index.html carries no JSON-LD block');
for (const block of ldBlocks) {
  try {
    const parsed = JSON.parse(block);
    const types = [parsed['@type']].flat().filter(Boolean);
    if (!types.length) failures.push('a JSON-LD block in index.html declares no @type');
    if (types.includes('Person')) {
      if (!Array.isArray(parsed.sameAs) || !parsed.sameAs.length) {
        failures.push('the Person block declares no sameAs — the identity it describes is unreachable');
      }
      if (!String(parsed.email ?? '').includes('@')) failures.push('the Person block carries no email');
    }
  } catch (error) {
    failures.push(`a JSON-LD block in index.html is not valid JSON: ${error.message}`);
  }
}
if (!index.includes('href="/llms.txt"')) {
  failures.push('index.html does not link /llms.txt, so the file it ships is undiscoverable');
}

// ── Share card ────────────────────────────────────────────────────────────────
// The card is generated (`npm run og`), so it is the one asset nobody looks at
// while designing a page — and the one most people see first. A wrong size is
// silently letterboxed or cropped by every unfurler, and a meta tag that points
// at a file the build does not ship means no card at all, so both are checked.
const CARD = { width: 1200, height: 630, path: '/og-image.png' };
const CARD_FILE = `public${CARD.path}`;
if (existsSync(CARD_FILE)) {
  // PNG puts the size in the IHDR chunk: 8 bytes of signature, 4 of length, 4 of
  // type, then width and height as big-endian uint32. No decoder needed.
  const header = readFileSync(CARD_FILE).subarray(0, 24);
  const isPng = header.subarray(1, 4).toString('ascii') === 'PNG';
  if (!isPng) {
    failures.push(`${CARD_FILE} is not a PNG, and every unfurler keys on the declared type`);
  } else {
    const width = header.readUInt32BE(16);
    const height = header.readUInt32BE(20);
    if (width !== CARD.width || height !== CARD.height) {
      failures.push(
        `${CARD_FILE} is ${width}x${height}; share cards are ${CARD.width}x${CARD.height} and every platform crops or letterboxes the rest — run \`npm run og\``,
      );
    }
  }
}
for (const token of [
  `property="og:image" content="https://camtaylor.ca${CARD.path}"`,
  `name="twitter:image" content="https://camtaylor.ca${CARD.path}"`,
  `property="og:image:width" content="${CARD.width}"`,
  `property="og:image:height" content="${CARD.height}"`,
  'property="og:image:alt"',
  'name="twitter:image:alt"',
  'name="twitter:card" content="summary_large_image"',
]) {
  if (!index.includes(token)) failures.push(`The share card is not declared in index.html: ${token}`);
}
if (!index.includes('name="twitter:site"')) {
  failures.push('Missing metadata: name="twitter:site" — an unowned card is credited to nobody');
}

// ── Per-page share cards ──────────────────────────────────────────────────────
// Every dispatch and every venture route has its own card, generated by `npm run og` from
// that page's own words. The failure this gate prevents is silent and invisible in a
// browser: a slug whose card was never generated renders perfectly on the site and shows a
// missing image in every feed it is shared into.
function jpegSize(file) {
  const buffer = readFileSync(file);
  // SOF0/SOF2 carry the frame size; walk the markers rather than decoding the pixels.
  if (buffer[0] !== 0xff || buffer[1] !== 0xd8) return null;
  let offset = 2;
  while (offset + 9 < buffer.length) {
    if (buffer[offset] !== 0xff) {
      offset += 1;
      continue;
    }
    const marker = buffer[offset + 1];
    if (marker >= 0xc0 && marker <= 0xc3) {
      return { height: buffer.readUInt16BE(offset + 5), width: buffer.readUInt16BE(offset + 7) };
    }
    offset += 2 + buffer.readUInt16BE(offset + 2);
  }
  return null;
}

const dispatchSlugs = readdirSync('src/content/dispatches')
  .filter((file) => file.endsWith('.md'))
  .filter((file) => !/^draft:\s*true/im.test(readFileSync(join('src/content/dispatches', file), 'utf8')))
  .map((file) => {
    const source = readFileSync(join('src/content/dispatches', file), 'utf8');
    return /^slug:\s*(.+)$/im.exec(source)?.[1]?.trim().replace(/^["']|["']$/g, '')
      || file.replace(/\.md$/, '').replace(/^\d{4}-\d{2}-\d{2}-/, '');
  });
const ventureIds = [...readFileSync('src/data/ventures.ts', 'utf8').matchAll(/\bid:\s*'([a-z0-9-]+)'/g)].map(
  (match) => match[1],
);
for (const slug of [...dispatchSlugs, ...ventureIds]) {
  const file = `public/og/${slug}.jpg`;
  if (!existsSync(file)) {
    failures.push(`${file} is missing — run \`npm run og\`, or that page shares no card at all`);
    continue;
  }
  const size = jpegSize(file);
  if (!size) failures.push(`${file} is not a JPEG`);
  else if (size.width !== CARD.width || size.height !== CARD.height) {
    failures.push(`${file} is ${size.width}x${size.height}, not ${CARD.width}x${CARD.height}`);
  }
}

const envExample = readFileSync('.env.example', 'utf8');
if (!envExample.includes('VITE_PRIVATE_PREVIEW=true')) failures.push('Private preview must default to true');

const robots = readFileSync('public/robots.txt', 'utf8');
if (!robots.includes('Sitemap:')) failures.push('robots.txt must declare a sitemap');

// Preview copy must never be hard-coded: every mention has to sit behind
// IS_PRIVATE_PREVIEW, or a public build will announce itself as a preview.
function walk(dir, extensions = ['.tsx']) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) return walk(path, extensions);
    return extensions.some((extension) => entry.name.endsWith(extension)) ? [path] : [];
  });
}

for (const file of walk('src')) {
  const source = readFileSync(file, 'utf8');
  if (/private preview/i.test(source) && !source.includes('IS_PRIVATE_PREVIEW')) {
    failures.push(`${file} mentions the private preview without gating it on IS_PRIVATE_PREVIEW`);
  }
}

// ── Type-scale guard ───────────────────────────────────────────────────────────────
// This site had 56 bespoke font sizes, most of them between 8px and 11.5px. They now
// come from the seven-step scale in `src/index.css`, and nothing a visitor reads may
// sit below the floor. A fresh sub-floor literal fails the build so the scale cannot
// quietly grow back — the same instrument-first pattern as `tests/contrast.spec.ts`.
const FLOOR_REM = 0.6875; // --fs-2xs, the one documented exception (uppercase micro-labels)
const FLOOR_PX = 11;
const SIZE_PATTERNS = [/font-size:\s*([^;]+);/g, /(?:^|[;{\s])font:\s*([^;]+);/g];

for (const file of walk('src', ['.css'])) {
  readFileSync(file, 'utf8')
    .split('\n')
    .forEach((line, index) => {
      for (const pattern of SIZE_PATTERNS) {
        pattern.lastIndex = 0;
        let match;
        while ((match = pattern.exec(line)) !== null) {
          const value = match[1].trim();
          const rem = value.match(/(\d*\.?\d+)rem/);
          const px = value.match(/(\d*\.?\d+)px/);
          const belowFloor = rem ? Number(rem[1]) < FLOOR_REM : px ? Number(px[1]) < FLOOR_PX : false;
          if (belowFloor) {
            failures.push(
              `${file}:${index + 1} sets "${value}" below the ${FLOOR_REM}rem / ${FLOOR_PX}px type floor — use a --fs-* token`,
            );
          }
        }
      }
    });
}

// ── Cascade guard ─────────────────────────────────────────────────────────────
// Six stylesheets load in a fixed order (`src/main.tsx`), so a rule written in
// the wrong one is not a style change — it is a declaration that never applies,
// and nothing in a screenshot or a diff says so. Twenty were found by hand and
// removed when this guard landed; it is here so the next one fails the build
// instead. `npm run cascade` prints the full picture, including the rings this
// cannot gate on and the reasons it can never see everything.
for (const entry of atRuleDeclarationsThatNeverApply(stylesheetOrder())) {
  failures.push(`a phone override that never applies at any width — ${describe(entry)}`);
}

// ── The contact form's destination ──────────────────────────────────────────────
// The form hands a stranger's message to Formspree, which delivers it to exactly one
// inbox: `INQUIRY_EMAIL` in `src/data/site.ts`, the address Kimi monitors so she can
// filter the spam before any of it reaches Cam. Three things have to agree with that
// one string — the public `familyEmail`, the copy on the page, and the env template
// the deployer actually reads. This gate exists because the page stated a delivery
// address the endpoint did not deliver to, and nothing said so.
const siteSource = readFileSync('src/data/site.ts', 'utf8');
const inbox = siteSource.match(/export const INQUIRY_EMAIL = '([^']+)'/)?.[1];
if (!inbox) {
  failures.push(
    'src/data/site.ts must export INQUIRY_EMAIL — the one inbox a contact-form submission is delivered to',
  );
} else {
  if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(inbox)) failures.push(`INQUIRY_EMAIL is not an address: ${inbox}`);
  if (!siteSource.includes('familyEmail: INQUIRY_EMAIL')) {
    failures.push(
      'SITE.familyEmail must be INQUIRY_EMAIL, or the public address and the form destination can drift apart',
    );
  }
  if (!envExample.includes(inbox)) {
    failures.push(`.env.example no longer tells the deployer the form must deliver to ${inbox}`);
  }
}

// The subject line is how Kimi's shared inbox tells camtaylor submissions apart from the
// sibling sites that deliver to the same address, and the failure path's mailto has to be
// filterable too. One function builds it, so the hidden field and the mailto cannot drift —
// and a second literal subject anywhere is exactly how one of them would lose the prefix.
const contactSource = readFileSync('src/components/Contact.tsx', 'utf8');
if (!siteSource.includes('`[camtaylor.ca] New inquiry — ')) {
  failures.push('INQUIRY_SUBJECT in src/data/site.ts no longer prefixes the subject with [camtaylor.ca], which is what makes camtaylor submissions filterable in the shared inbox');
}
if (/New inquiry — /.test(contactSource)) {
  failures.push('src/components/Contact.tsx builds its own subject — the hidden _subject field and the mailto fallback must both use INQUIRY_SUBJECT, or one of them silently loses the prefix');
}

// ── Analytics, if it is ever switched on ───────────────────────────────────────────
// `trackEvent` was a no-op for a whole release: nothing ever loaded an analytics script,
// so `form_start`, `form_submit` and `form_success` went nowhere and the form's own
// conversion was invisible — the same shape as the contact form reporting nothing while
// being broken. The loader exists now, and the one thing that silently breaks it is a
// host missing from the CSP, where a blocked script looks exactly like no analytics.
//
// The loader can reach two hosts (Plausible, and the family's self-hosted Umami), because
// which one camtaylor uses is an open question for Kimi. Both are checked, because the
// second one is not the one that gets tested — a set `VITE_UMAMI_WEBSITE_ID` against a CSP
// that only allows plausible.io is a script the browser blocks in silence.
const analyticsPath = join('src', 'utils', 'analytics.ts');
const analyticsSource = readFileSync(analyticsPath, 'utf8');
const hostList = analyticsSource.match(/ANALYTICS_HOSTS = \[([\s\S]*?)\]/)?.[1] ?? '';
const analyticsHosts = [...hostList.matchAll(/'https:\/\/([a-z0-9.-]+)'/g)].map((match) => match[1]);
if (!analyticsHosts.length) {
  failures.push('src/utils/analytics.ts no longer lists ANALYTICS_HOSTS, so the CSP cannot be checked against it');
} else {
  const headers = readFileSync('public/_headers', 'utf8');
  for (const host of analyticsHosts) {
    for (const directive of ['script-src', 'connect-src']) {
      const policy = headers.match(new RegExp(`${directive}[^;]*`))?.[0] ?? '';
      if (!policy.includes(host)) {
        failures.push(`public/_headers ${directive} does not allow ${host} — the analytics script would be blocked in production`);
      }
    }
  }
  // One loader, or two scripts load. This repo briefly had two — a React effect in
  // `src/components/Analytics.tsx` loading Plausible's plain script and `initAnalytics()`
  // loading the tagged-events one — which is one pageview reported twice the moment
  // analytics is switched on, and invisible in a browser either way. The pattern is a script
  // URL, not a bare hostname, so prose that merely names the provider (the privacy policy
  // does) is not a second loader.
  const scriptUrl = new RegExp(
    `https://(?:${analyticsHosts.map((host) => host.replace(/\./g, '\\.')).join('|')})/[^'"\`\\s]*script`,
    'i',
  );
  // Every allowed host has to be one the loader actually loads from, or the policy is dead.
  for (const host of analyticsHosts) {
    const url = new RegExp(`https://${host.replace(/\./g, '\\.')}/[^'"\`\\s]*script`, 'i');
    if (!url.test(analyticsSource)) {
      failures.push(`${analyticsPath} never loads a script from ${host}, so allowing it in the CSP guards nothing`);
    }
  }
  for (const file of walk('src', ['.ts', '.tsx'])) {
    if (file === analyticsPath) continue;
    if (scriptUrl.test(readFileSync(file, 'utf8'))) {
      failures.push(`${file} loads an analytics script of its own — every analytics script must be created in ${analyticsPath}, or two loaders load two scripts`);
    }
  }
}

if (failures.length) {
  console.error(failures.map((failure) => `✗ ${failure}`).join('\n'));
  process.exit(1);
}
console.log(
  `✓ Quality check passed (${requiredFiles.length} assets, ${CARD.width}x${CARD.height} share card, metadata, privacy gate, type-scale floor, cascade, form inbox, analytics hosts)`,
);
